config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'companies/:id/company_taxpayers', to: 'companies#company_taxpayers', as: :company_taxpayers
  get 'year_index', to: 'taxpayers#year_index'
  get 'inactive_taxpayers', to: 'taxpayers#inactive'
  get 'active_taxpayers', to: 'taxpayers#active'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :taxpayers
  resources :users
  resources :companies
  resources :years
end

app/models/taxpayer.rb
require 'csv'
class Taxpayer < ApplicationRecord 
    
    belongs_to :company
    
    has_many :taxpayer_years
    has_many :years, through: :taxpayer_years
    
    validates :ird_no, uniqueness: true, presence: true, length: { is: 6 }
    validates :first_name, presence: true, length: {minimum: 3, maximum: 25}
    validates :last_name, presence: true, length: {minimum: 3, maximum: 25}
    validates :address, presence: true, length: {minimum: 3, maximum: 25}
    validates :entity_type, presence: true, inclusion: { in: %w[Self-Employed Government Private] }
    validates :activity_status, presence: true, inclusion: { in: %w[Active Inactive] }
    
    def self.to_csv
        CSV.generate do |csv|
            csv << column_names
            all.each do |taxpayer|
                csv << taxpayer.attributes.values_at(*column_names)
            end
        end
    end
end

app/controllers/taxpayers_controller.rb
class TaxpayersController < ApplicationController
    
    before_action :set_taxpayer, only: [:show, :edit, :update, :destroy]
    before_action :require_user, only: [:show, :edit, :update, :destroy, :new, :create, :index]
    before_action :require_registrar_admin, only: [:edit, :update, :new, :create, :destroy]
    
    
    
    
    def show
    
    end
    
    def index
        @q = Taxpayer.ransack(params[:q])
        @results = @q.result(distinct: true)
        @taxpayers = @results.paginate(page: params[:page], per_page: 15)
    end
    
    def new
        @taxpayer = Taxpayer.new
    end
    
    def create
        @taxpayer = Taxpayer.new(taxpayer_params)
        if @taxpayer.save
            redirect_to taxpayer_path(@taxpayer)
            flash[:notice] = "Taxpayer was created successfully"
        else 
            render 'new'
        end
    end
    
    def edit 
    end
    
    def update
        if @taxpayer.update(taxpayer_params)
            flash[:notice] = "Taxpayer was updated successfully"
            redirect_to @taxpayer
        else
            render 'edit'
        end
    end
    
    def destroy 
        @taxpayer.destroy
        redirect_to taxpayers_path
    end
    
    
    def year_index
        @q = Taxpayer.ransack(params[:q])
        @results = @q.result(distinct: true)
        @taxpayers = @results.paginate(page: params[:page], per_page: 15)
    end
    
    def inactive
        @q = Taxpayer.where(activity_status: 'Inactive').ransack(params[:q])
        @results = @q.result(distinct: true)
        @taxpayers = @results.paginate(page: params[:page], per_page: 15)
    end
    
    def active
        @q = Taxpayer.where(activity_status: 'Active').ransack(params[:q])
        @results = @q.result(distinct: true)
        @taxpayers = @results.paginate(page: params[:page], per_page: 15)
    end
    
    private
    
    def set_taxpayer
        @taxpayer = Taxpayer.find(params[:id])
    end
    
    def taxpayer_params
        params.require(:taxpayer).permit(:ird_no, :old_ird_no, :first_name, :middle_name, :last_name, :address, :entity_type, :activity_status, :company_id, year_ids: [])
    end
    
    def redirect_to_index
        redirect_to taxpayers_path
    end
    
    helper_method :redirect_to_index
    
end

app/views/taxpayers/_search_form.html.erb
<%= search_form_for obj do |f| %>

    <%= f.search_field :ird_no_or_company_id_or_first_name_or_last_name_or_address_or_entity_type_or_activity_status_or_company_name_cont %>
    
    <%= f.submit "Search" %>
<% end %>

app/views/taxpayers/active.html.erb
<div class="container ">
    <h1 class="mt-4"> Active Taxpayers </h1><br/>
    
    <% if logged_in? %>
      <div class="col-md-4">
          <div class="card card-sm">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="badge-primary p-2 pt-4 pb-4 rounded center">
                    <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
                      <path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                      <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Taxpayer.where(activity_status: 'Active').count %>
                  </div>
                  <div class="text-muted">
                    Active Taxpayers
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div><br/>
      
    
      <div class="row">
        <div class="col-lg">
          <div class="flickr_pagination">
              <%= will_paginate @taxpayers, :container => false %>
          </div> 
        </div>
        <div class="col-lg">
          <%= render 'taxpayers/search_form', obj: @q %>
        </div>
      </div>
  
      
      <table class="table table-striped  mt-4 ">
        <thead>
          <tr>
              <th>IRD Number</th>
              <th>Old IRD Number</th>
              <th>First Name</th>
              <th>Middle Name</th>
              <th>Last Name</th>
              <th>Address</th>
              <th>Entity Type</th>
              <th>Active Status</th>
              <th colspan="3">Actions</th>
          </tr>
        </thead>
          <tbody>
              <% Taxpayer.where(activity_status: 'Active').each do |taxpayer| %>
              <tr>
                  <td> <%= taxpayer.ird_no %> </td>
                  <td> <%= taxpayer.old_ird_no %></td>
                  <td><%= taxpayer.first_name %></td>
                  <td><%= taxpayer.middle_name %></td>
                  <td><%= taxpayer.last_name %></td>
                  <td><%= taxpayer.address %></td>
                  <td><%= taxpayer.entity_type %></td>
                  <td><%= taxpayer.activity_status %></td>
                  <td><%= link_to "View", taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                    <td><%= link_to 'Edit', edit_taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
      
      <div class="flickr_pagination">
          <%= will_paginate @taxpayers, :container => false %>
      </div> 
      
      <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
        <p><b> <%= link_to "Add new taxpayer", new_taxpayer_path, class:"alert alert-light" %> </b></p>
        <% end %>
    <% else %>
      <% redirect_to_index %>
    <% end %>
</div>

app/views/taxpayers/inactive.html.erb
<div class="container">
    <h1 class="mt-4"> Inactive Taxpayers </h1><br/>
    
    <% if logged_in? %>
      <div class="col-md-4">
          <div class="card card-sm">
            <div class="card-body">
              <div class="row align-items-center">
                <div class="col-auto">
                  <span class="badge-primary p-2 pt-4 pb-4 rounded center">
                    <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
                    <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
                      <path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                      <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
                    </svg>
                  </span>
                </div>
                <div class="col">
                  <div class="font-weight-medium">
                    <%= Taxpayer.where(activity_status: 'Inactive').count %>
                  </div>
                  <div class="text-muted">
                    Inactive Taxpayers
                  </div>
                </div>
              </div>
            </div>
          </div>
      </div><br/>
      
      
      <div class="row">
        <div class="col-lg">
          <div class="flickr_pagination">
              <%= will_paginate @taxpayers, :container => false %>
          </div> 
        </div>
        <div class="col-lg">
          <%= render 'taxpayers/search_form', obj: @q %>
        </div>
      </div>
      
    
      <table class="table table-striped  mt-4">
        <thead>
          <tr>
              <th><%= sort_link(@q,:ird_no, "IRD Number", hide_indicator: true) %></th>
              <th><%= sort_link(@q,:company_id, "PAYE Number", hide_indicator: true) %></th>
              <th><%= sort_link(@q, :first_name, hide_indicator: true) %></th>
              <th>Middle Name</th>
              <th><%= sort_link(@q, :last_name, hide_indicator: true) %></th>
              <th><%= sort_link(@q, :address, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:company_id, "Company Name", hide_indicator: true) %></th>
              <th><%= sort_link(@q,:entity_type, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:activity_status, "Active Status", hide_indicator: true) %></th>
              <th colspan="3", class="text-center">Actions</th>
          </tr>
        </thead>
          <tbody>
              <% Taxpayer.where(activity_status: 'Inactive').each do |taxpayer| %>
              <tr>
                  <td> <%= taxpayer.ird_no %> </td>
                  <td> <%= taxpayer.company.paye_no %></td>
                  <td><%= taxpayer.first_name %></td>
                  <td><%= taxpayer.middle_name %></td>
                  <td><%= taxpayer.last_name %></td>
                  <td><%= taxpayer.address %></td>
                  <td><%= taxpayer.company.name %></td>
                  <td><%= taxpayer.entity_type %></td>
                  <td><%= taxpayer.activity_status %></td>
                  <td><%= link_to "View", taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                    <td><%= link_to 'Edit', edit_taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
      
      <div class="flickr_pagination">
          <%= will_paginate @taxpayers, :container => false %>
      </div>
      
      <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
        <p><b> <%= link_to "Add new taxpayer", new_taxpayer_path, class:"alert alert-light" %> </b></p>
        <% end %>
    <% else %>
      <% redirect_to_index %>
    <% end %>
</div>

app/views/taxpayers/index.html.erb
<div class="container">
    <h1 class="mt-4"> All Taxpayers </h1><br/>
    
    <% if logged_in? %>
    <div class="col-5">
      <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-auto">
            <span class="badge-primary p-2 pt-4 pb-4 rounded center">
              <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
                <path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
            </span>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.count %>
            </div>
            <div class="text-muted">
              Total Taxpayers
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Active').count %>
            </div>
            <div class="text-muted">
              <%= link_to 'Active Taxpayers', active_taxpayers_path %>
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Inactive').count %>
            </div>
            <div class="text-muted">
              <%= link_to 'Inactive Taxpayers', inactive_taxpayers_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Government').count %>
            </div>
            <div class="text-muted">
            Government
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Private').count %>
            </div>
            <div class="text-muted">
              Private
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Self-Employed').count %>
            </div>
            <div class="text-muted">
              Self-employed
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
    </br></br>
    
    <!-- search form -->

      <div class="row">
        <div class="col-lg">
          <div class="flickr_pagination">
              <%= will_paginate @taxpayers, :container => false %>
          </div> 
        </div>
        <div class="col-lg">
          <%= render 'taxpayers/search_form', obj: @q %>
        </div>
      </div>
      
      
      
      <table class="table table-striped  mt-4">
        <thead>
          <tr>
              <th><%= sort_link(@q,:ird_no, "IRD Number", hide_indicator: true) %></th>
              <th><%= sort_link(@q,:company_id, "PAYE Number", hide_indicator: true) %></th>
              <th><%= sort_link(@q, :first_name, hide_indicator: true) %></th>
              <th>Middle Name</th>
              <th><%= sort_link(@q, :last_name, hide_indicator: true) %></th>
              <th><%= sort_link(@q, :address, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:company_id, "Company Name", hide_indicator: true) %></th>
              <th><%= sort_link(@q,:entity_type, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:activity_status, "Active Status", hide_indicator: true) %></th>
              <th colspan="3", class="text-center">Actions</th>
          </tr>
        </thead>
          <tbody>
              <% @taxpayers.each do |taxpayer| %>
              <tr>
                  <td> <%= taxpayer.ird_no %> </td>
                  <td> <%= taxpayer.company.paye_no %></td>
                  <td><%= taxpayer.first_name %></td>
                  <td><%= taxpayer.middle_name %></td>
                  <td><%= taxpayer.last_name %></td>
                  <td><%= taxpayer.address %></td>
                  <td><%= taxpayer.company.name %></td>
                  <td><%= taxpayer.entity_type %></td>
                  <td><%= taxpayer.activity_status %></td>
                  <td><%= link_to "View", taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                    <td><%= link_to 'Edit', edit_taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
      
      <div class="flickr_pagination mb-4">
          <%= will_paginate @taxpayers, :container => false %>
      </div> 
      
      
      <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
        <p><b> <%= link_to "Add new taxpayer", new_taxpayer_path, class:"alert alert-light" %> </b></p>
        <% end %>
      <% else %>
      <% redirect_to_index %>
    <% end %>
</div>

app/views/taxpayers/show.html.erb
<div class="container">
    <h1 class="mt-4"> Taxpayer Information </h1></br>
    
    <!--<p><strong> IRD No: </strong></p> <%= @taxpayer.ird_no %>
    <p><strong> Old IRD No: </strong></p> <%= @taxpayer.old_ird_no %>
    <p><strong> First Name: </strong></p> <%= @taxpayer.first_name %>
    <p><strong> Middle Name: </strong></p> <%= @taxpayer.middle_name %>
    <p><strong> Surname: </strong></p> <%= @taxpayer.last_name %>
    <p><strong> Address: </strong></p> <%= @taxpayer.address %>
    <p><strong> Entity Type: </strong></p> <%= @taxpayer.entity_type %>
    <p><strong> Active Status: </strong></p> <%= @taxpayer.activity_status %>
    <p><strong> Created At:: </strong></p> <%= @taxpayer.created_at %>
    <p><strong> Updated At:: </strong></p> <%= @taxpayer.updated_at %>-->
    
    
    <div class="card mt-4" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title"><%= @taxpayer.first_name %>  <%= @taxpayer.middle_name %>  <%= @taxpayer.last_name %></h5></br>
            <h6 class="card-subtitle mb-2 text-muted">IRD Number: <%= @taxpayer.ird_no %> | Old IRD Number: <%= @taxpayer.old_ird_no %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Address: <%= @taxpayer.address %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted"> Company: <%= link_to @taxpayer.company.name, company_path(@taxpayer.company) %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Entity Type: <%= @taxpayer.entity_type %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Active Status: <%= @taxpayer.activity_status %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Years Assessed: 
            
                <% if @taxpayer.years.any? %>
                    <%= render @taxpayer.years %>
                 </h6>
                 <% end %>
            
            
            </br></br><p class="card-text">Created on: <%= @taxpayer.created_at %></p>
            <p class="card-text">Last updated on: <%= @taxpayer.updated_at %></p>
            <% if logged_in? %>
                <% if current_user.access_level == "Registrar" or current_user.access_level == "Admin" %>
                    <%= link_to 'Edit', edit_taxpayer_path(@taxpayer), class:"btn btn-outline-primary btn-sm" %>
                    <% if current_user.access_level == "Admin" %>
                        <%= link_to 'Delete', taxpayer_path(@taxpayer), class:"btn btn-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %>
                    <% end %>
                <% end %>
            <% end %>
          </div>
        </div></br>
        
    <p>
        <%= link_to "Return to taxpayers listing", taxpayers_path %>
    </p>
        

</div>

app/views/taxpayers/year_index.html.erb
<div class="container">
    <h1 class="mt-4"> Year Register </h1><br/>
    
    <% checkmark = "\u2713" %>
    
    
         <% if logged_in? %>
      <div class="col-5">
           <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-auto">
            <span class="badge-primary p-2 pt-4 pb-4 rounded center">
              <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
                <path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
            </span>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.count %>
            </div>
            <div class="text-muted">
              Total Taxpayers
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Active').count %>
            </div>
            <div class="text-muted">
              Active Taxpayers
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Inactive').count %>
            </div>
            <div class="text-muted">
              Inactive Taxpayers
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Year.joins(:taxpayers).where(name: '2017').count %>
            </div>
            <div class="text-muted">
            2017
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Year.joins(:taxpayers).where(name: '2018').count %>
            </div>
            <div class="text-muted">
              2018
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Year.joins(:taxpayers).where(name: '2019').count %>
            </div>
            <div class="text-muted">
              2019
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Year.joins(:taxpayers).where(name: '2020').count %>
            </div>
            <div class="text-muted">
            2020
            </div>
          </div><div class="col">
            <div class="font-weight-medium">
              <%= Year.joins(:taxpayers).where(name: '2021').count %>
            </div>
            <div class="text-muted">
            2021
            </div>
          </div>
        </div>
      </div>
    </div></div>
    <br/>
    
    <div class="row">
      <div class="col-lg">
        <div class="flickr_pagination">
            <%= will_paginate @taxpayers, :container => false %>
        </div> 
      </div>
      <div class="col-lg">
        <%= render 'taxpayers/search_form', obj: @q %>
      </div>
    </div>
  
      
      <table class="table table-striped  mt-4 ">
        <thead>
          <tr>
              <th><%= sort_link(@q,:ird_no, "IRD Number", hide_indicator: true) %></th>
              <th><%= sort_link(@q, :first_name, hide_indicator: true) %></th>
              <th>Middle Name</th>
              <th><%= sort_link(@q, :last_name, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:entity_type, hide_indicator: true) %></th>
              <th><%= sort_link(@q,:activity_status, "Active Status", hide_indicator: true) %></th>
              <th>2017</th>
              <th>2018</th>
              <th>2019</th>
              <th>2020</th>
              <th>2021</th>
              
              <th colspan="3">Actions</th>
          </tr>
        </thead>
          <tbody>
              <% @taxpayers.where(activity_status: 'Active').each do |taxpayer| %>
              <tr>
                  <td> <%= taxpayer.ird_no %> </td>
                  <td><%= taxpayer.first_name %></td>
                  <td><%= taxpayer.middle_name %></td>
                  <td><%= taxpayer.last_name %></td>
                  <td><%= taxpayer.entity_type %></td>
                  <td><%= taxpayer.activity_status %></td>
                  
                  <td>
                    <% if taxpayer.year_ids.include?(1) %>
                      <%= checkmark %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                  
                  
                  <td>
                    <% if taxpayer.year_ids.include?(2) %>
                      <%= checkmark %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                  
                  
                  <td>
                    <% if taxpayer.year_ids.include?(3) %>
                      <%= checkmark %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                  
                  
                  <td>
                    <% if taxpayer.year_ids.include?(4) %>
                      <%= checkmark %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                  
                  
                  <td>
                    <% if taxpayer.year_ids.include?(5) %>
                      <%= checkmark %>
                    <% else %>
                      -
                    <% end %>
                  </td>
                  
                  <td><%= link_to "View", taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                    <td><%= link_to 'Edit', edit_taxpayer_path(taxpayer), class:"btn btn-outline-primary btn-sm" %></td>
                  <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
      <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
        <p><b> <%= link_to "Add new taxpayer", new_taxpayer_path, class:"alert alert-light" %> </b></p>
        <% end %>
    <% else %>
      <% redirect_to_index %>
    <% end %>
</div>