config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'companies/:id/company_taxpayers', to: 'companies#company_taxpayers', as: :company_taxpayers
  get 'year_index', to: 'taxpayers#year_index'
  get 'inactive_taxpayers', to: 'taxpayers#inactive'
  get 'active_taxpayers', to: 'taxpayers#active'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :taxpayers
  resources :users
  resources :companies
  resources :years
end

app/views/pages/about.html.erb
<h1> About Page </h1>

<p><%= link_to 'Home', root_path %> </p>
<p><%= link_to "Articles listing", taxpayers_path %></p>

app/views/pages/home.html.erb
<div class="container" id="home-container">
    <p>OVERVIEW</p>
    <h2>Dashboard</h2><br/>

   <div class="row justify-content-start">
    <div class="col-5">
      <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-auto">
            <span class="badge-primary p-2 pt-4 pb-4 rounded center">
              <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-file-person" viewBox="0 0 16 16">
                <path d="M12 1a1 1 0 0 1 1 1v10.755S12 11 8 11s-5 1.755-5 1.755V2a1 1 0 0 1 1-1h8zM4 0a2 2 0 0 0-2 2v12a2 2 0 0 0 2 2h8a2 2 0 0 0 2-2V2a2 2 0 0 0-2-2H4z"/>
                <path d="M8 10a3 3 0 1 0 0-6 3 3 0 0 0 0 6z"/>
              </svg>
            </span>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.count %>
            </div>
            <div class="text-muted">
              Total Taxpayers
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Active').count %>
            </div>
            <div class="text-muted">
              <%= link_to 'Active Taxpayers', active_taxpayers_path %>
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(activity_status: 'Inactive').count %>
            </div>
            <div class="text-muted">
              <%= link_to 'Inactive Taxpayers', inactive_taxpayers_path %>
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Government').count %>
            </div>
            <div class="text-muted">
            Government
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Private').count %>
            </div>
            <div class="text-muted">
              Private
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Taxpayer.where(entity_type: 'Self-Employed').count %>
            </div>
            <div class="text-muted">
              Self-employed
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card" style="height: calc(24rem + 10px)">
        <div class="card-body card-body-scrollable card-body-scrollable-shadow">
          <h3 class="card-title">Recent Taxpayers</h3>
          <div class="card-subtitle">
            Showing recent taxpayers
          </div>
          <div class="divide-y">
            <% Taxpayer.last(10).reverse.each do |taxpayer| %>
              <div>
                <div class="row">
                  <div class="col-auto">
                    
                  </div>
                  <div class="col">
                    <div class="text-truncate">
                      <%= link_to "#{taxpayer.first_name} #{taxpayer.middle_name} #{taxpayer.last_name}", taxpayer_path(taxpayer) %>
                    </div>
                  </div>
                  <div class="col-auto">
                  </div>
                </div><!--/.row-->
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    
    
    <div class="col-5">
       <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-auto">
            <span class="badge-primary p-2 pt-4 pb-4 rounded center">
              <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
              </svg>
            </span>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.count %>
            </div>
            <div class="text-muted">
              Total Companies
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(activity_status: 'Active').count %>
            </div>
            <div class="text-muted">
              Active Companies
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(activity_status: 'Inactive').count %>
            </div>
            <div class="text-muted">
              Inactive Companies
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Government').count %>
            </div>
            <div class="text-muted">
            Government
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Private').count %>
            </div>
            <div class="text-muted">
              Private
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Self-Employed').count %>
            </div>
            <div class="text-muted">
              Self-employed
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card" style="height: calc(24rem + 10px)">
        <div class="card-body card-body-scrollable card-body-scrollable-shadow">
          <h3 class="card-title">Recent Companies</h3>
          <div class="card-subtitle">
            Showing recent companies
          </div>
          <div class="divide-y">
            <% Company.last(10).reverse.each do |company| %>
              <div>
                <div class="row">
                  <div class="col-auto">
                    
                  </div>
                  <div class="col">
                    <div class="text-truncate">
                      <%= link_to "#{company.name}", company_path(company) %>
                    </div>
                  </div>
                  <div class="col-auto">
                  </div>
                </div><!--/.row-->
              </div>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
    
  <br>
  <p><%= link_to "Taxpayer Listing", taxpayers_path %> | <%= link_to "Company Listing", companies_path %></p>
</div>