config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'companies/:id/company_taxpayers', to: 'companies#company_taxpayers', as: :company_taxpayers
  get 'year_index', to: 'taxpayers#year_index'
  get 'inactive_taxpayers', to: 'taxpayers#inactive'
  get 'active_taxpayers', to: 'taxpayers#active'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :taxpayers
  resources :users
  resources :companies
  resources :years
end

app/models/company.rb
class Company < ApplicationRecord
    
    has_many :taxpayers
    
    validates :ird_no, uniqueness: true, presence: true, length: {minimum: 6, maximum: 6}
    validates :name, presence: true, length: {minimum: 3, maximum: 25}
    validates :address, presence: true, length: {minimum: 3, maximum: 25}
    validates :entity_type, presence: true, inclusion: { in: %w[Self-Employed Government Private] }
    validates :activity_status, presence: true, inclusion: { in: %w[Active Inactive] }
    validates :paye_no, uniqueness: true, presence: true
end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
    
    before_action :set_company, only: [:show, :edit, :update, :destroy, :company_taxpayers]
    before_action :require_user, only: [:show, :edit, :update, :destroy, :new, :create, :index]
    before_action :require_registrar_admin, only: [:edit, :update, :new, :create, :destroy]
    
    def index
        @q = Company.ransack(params[:q])
        @results = @q.result(distinct: true)
        @companies = @results.paginate(page: params[:page], per_page: 15)
    end
    
    def new
        @company = Company.new
    end
    
    def create
        @company = Company.new(company_params)
        if @company.save
            redirect_to company_path(@company)
            flash[:notice] = "Company was created successfully"
        else 
            render 'new'
        end
    end
    
    def edit 
    end
    
    def update
        if @company.update(company_params)
            flash[:notice] = "Company was updated successfully"
            redirect_to @company
        else
            render 'edit'
        end
    end
    
    def show
    end
    
    def destroy 
        @company.destroy
        redirect_to companies_path
    end
    
    def company_taxpayers
        @taxpayers = @company.taxpayers
        @companies = Company.all
        respond_to do |format|
            format.html
            format.csv { send_data @taxpayers.to_csv }
        end
    end
    
     private
    
    def set_company
        @company = Company.find(params[:id])
    end
    
    def company_params
        params.require(:company).permit(:ird_no, :name, :address, :entity_type, :activity_status, :paye_no)
    end
    
end

app/views/companies/_form.html.erb
<div class="col-10">
    <%= render 'shared/errors', obj: @company %>
</div>


<%= form_with(model: @company, local: true ) do |f| %>
    <div class="form-row">
        <div class="col-md-3 mb-3">
            <p> 
            <%= f.label 'IRD Number' %>
            <%= f.text_field :ird_no,  style: 'display: block;'%>
            </p>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-3 mb-3">
            <p> 
            <%= f.label 'Company Name' %>
            <%= f.text_field :name,  style: 'display: block;' %>
            </p>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-3 mb-3">
            <p> 
            <%= f.label 'Address' %>
            <%= f.text_field :address, style: 'display: block;' %>
            </p>
        </div>
    </div>
    
   <div class="form-row">
        <div class="col-md-3 mb-3">
            <p>
            <%= f.label 'PAYE Number' %>
            <%= f.text_field :paye_no, style: 'display block' %>
            </p>
        </div>
    </div>
    <div class="form-row">
        <div class="col-md-3 mb-3">
            <p>
            <%= f.label 'Entity Type' %>
            <%= f.select :entity_type, ['Government', 'Private', 'Self-Employed'] %>
            </p>
        </div>
        <div class="col-md-3 mb-3">
            <p>
            <%= f.label 'Activity Status' %>
            <%= f.select :activity_status, ['Active', 'Inactive'], style: 'display: block;'%>
            </p>
        </div>
    </div>
    
    <p>
        <%= f.submit %>
    </p>

<% end %>

app/views/companies/_search_form.html.erb
<%= search_form_for obj do |f| %>

    <%= f.search_field :ird_no_or_name_or_address_or_entity_type_or_activity_status_or_paye_no_cont %>
    
    <%= f.submit "Search" %>
<% end %>

app/views/companies/_taxpayers.html.backup.erb
<% @company.taxpayers.each do |company| %>
    <div class=" d-inline-flex d-flex justify-content-center page-break ">
       <div class="row d-table-row neg-row small-text p-0 m-0">
           <div class="col d-table-cell py-0"><strong> <%= company.first_name + " " + company.last_name %></strong></div>
        </div>
        <div class="row d-table-row neg-row small-text">
            <div class="col d-table-cell py-0"> <%= company.address %></div>
        </div>
        <div class="row d-table-row neg-row small-text p-0 m-0">
           <div class="col w-25 d-table-cell py-0"> PAYE: <%= company.company.paye_no %></div>
           <div class="col w-25 d-table-cell py-0">  <%= company.ird_no %> </div>
       </div>
    </div>
<% end %>

app/views/companies/_taxpayers.html.erb
<% @company.taxpayers.each do |company| %>
    <div class="page-break ">
        <p class = 'top-text' > <strong> <%= company.first_name + " " + company.last_name %></strong> </p>
        <div class="small-text">
           
           <p> <%= company.company.paye_no %> </p>
           <p> <%= company.company.name %> </p>
           <p> <%= company.address %> </p>
           <p> <%= company.ird_no %> </p>
        </div>
    </div>
<% end %>         

app/views/companies/company_taxpayers.html.erb
<div class="container">
    <%= render 'companies/taxpayers' %><br/>
</div>

app/views/companies/edit.html.erb
<div class="container">
    <h1> Edit Company </h1>
    
    <%= render 'form' %>
    
    <p><%= link_to "Return to companies listing", companies_path %></p>
</div>

app/views/companies/index.html.erb
<div class="container">
    <h1 class="mt-4"> All Companies </h1><br/>
    
    <% if logged_in? %>
     <div class="col-5">
      <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col-auto">
            <span class="badge-primary p-2 pt-4 pb-4 rounded center">
              <!--<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="24" height="24" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"></path><path d="M16.7 8a3 3 0 0 0 -2.7 -2h-4a3 3 0 0 0 0 6h4a3 3 0 0 1 0 6h-4a3 3 0 0 1 -2.7 -2"></path><path d="M12 3v3m0 12v3"></path></svg>-->
              <svg xmlns="http://www.w3.org/2000/svg" width="50" height="50" fill="currentColor" class="bi bi-house-fill" viewBox="0 0 16 16">
                <path fill-rule="evenodd" d="m8 3.293 6 6V13.5a1.5 1.5 0 0 1-1.5 1.5h-9A1.5 1.5 0 0 1 2 13.5V9.293l6-6zm5-.793V6l-2-2V2.5a.5.5 0 0 1 .5-.5h1a.5.5 0 0 1 .5.5z"/>
                <path fill-rule="evenodd" d="M7.293 1.5a1 1 0 0 1 1.414 0l6.647 6.646a.5.5 0 0 1-.708.708L8 2.207 1.354 8.854a.5.5 0 1 1-.708-.708L7.293 1.5z"/>
              </svg>
            </span>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.count %>
            </div>
            <div class="text-muted">
              Total Companies
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(activity_status: 'Active').count %>
            </div>
            <div class="text-muted">
              Companies Taxpayers
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(activity_status: 'Inactive').count %>
            </div>
            <div class="text-muted">
              Inactive Companies
            </div>
          </div>
        </div>
      </div>
    </div>
    <div class="card card-sm">
      <div class="card-body">
        <div class="row align-items-center">
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Government').count %>
            </div>
            <div class="text-muted">
            Government
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Private').count %>
            </div>
            <div class="text-muted">
              Private
            </div>
          </div>
          <div class="col">
            <div class="font-weight-medium">
              <%= Company.where(entity_type: 'Self-Employed').count %>
            </div>
            <div class="text-muted">
              Self-employed
            </div>
          </div>
        </div>
      </div>
    </div></div>
    </br></br>
      
      <div class="row">
        <div class="col-lg">
          <div class="flickr_pagination">
              <%= will_paginate @companies, :container => false %>
          </div> 
        </div>
        <div class="col-lg">
          <%= render 'companies/search_form', obj: @q %>
        </div>
      </div>

      
      <table class="table table-striped  mt-4">
        <thead>
          <tr>
              <th> <%= sort_link(@q, :ird_no, "IRD Number", default: :desc, hide_indicator: true) %> </th>
              <th> <%= sort_link(@q, :paye_no, "PAYE Number", default: :desc, hide_indicator: true) %> </th>
              <th><%= sort_link(@q, :name, "Company Name", hide_indicator: true) %></th>
              <th>Address</th>
              <th><%= sort_link(@q, :entity_type, "Entity Type", hide_indicator: true) %></th>
              <th><%= sort_link(@q, :activity_status, "Active Status", hide_indicator: true) %></th>
              <th colspan="3", class="text-center">Actions</th>
          </tr>
        </thead>
          <tbody>
              <% @companies.each do |company| %>
              <tr>
                  <td> <%= company.ird_no %> </td>
                  <td> <%= company.paye_no %> </td>
                  <td><%= company.name %></td>
                  <td><%= company.address %></td>
                  <td><%= company.entity_type %></td>
                  <td><%= company.activity_status %></td>
                  <td><%= link_to "Print Stickers", company_taxpayers_path(company, format: :csv), class:"btn btn-outline-primary btn-sm" %></td>
                  <td><%= link_to "View", company_path(company), class:"btn btn-outline-primary btn-sm" %></td>
                  <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                    <td><%= link_to 'Edit', edit_company_path(company), class:"btn btn-outline-primary btn-sm" %></td>
                  <% end %>
              </tr>
              <% end %>
          </tbody>
      </table>
      
      <div class="flickr_pagination mb-4 mt-4">
          <%= will_paginate @companies, :container => false %>
      </div></br>
      
      <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
        <p><b> <%= link_to "Add new company", new_company_path, class:"alert alert-light" %> </b></p>
        <% end %>
      <% else %>
      <% redirect_to_index %>
    <% end %>
</div>

app/views/companies/new.html.erb
<div class="container">
    <h1 class="mt-4"> New Company </h1></br>
    
    <%= render 'form' %></br>
    
    <p><%= link_to "Return to companies listing", companies_path %></p>
</div>

app/views/companies/show.html.erb
<div class="container">
    <h1 class="mt-4"> Company Information</h1> Information </h1></br>

    
    
    <div class="card mt-4" style="width: 50rem;">
        <div class="card-body">
            <h5 class="card-title"><%= @company.name %></h5></br>
            <h6 class="card-subtitle mb-2 text-muted">IRD Number: <%= @company.ird_no %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Address: <%= @company.address %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Entity Type: <%= @company.entity_type %></h6></br>
            <h6 class="card-subtitle mb-2 text-muted">Active Status: <%= @company.activity_status %></h6></br>
            
            <% if @company.taxpayers.any? %>
                <p> Company taxpayers: </p> <%= render @company.taxpayers %>
                </h6><br/>
            <% end %>
            
            
            
            <p class="card-text">Created on: <%= @company.created_at %></p>
            <p class="card-text">Last updated on: <%= @company.updated_at %></p>
            <% if logged_in? %>
                <% if current_user.access_level == "Registrar" or current_user.access_level == "Admin" %>
                    <%= link_to 'Edit', edit_company_path(@company), class:"btn btn-outline-primary btn-sm" %>
                    <% if current_user.access_level == "Admin" %>
                        <%= link_to 'Delete', company_path(@company), class:"btn btn-danger btn-sm", method: :delete, data: { confirm: "Are you sure?" } %>
                    <% end %>
                <% end %>
            <% end %>
          </div>
        </div></br>
        
    <p>
        <%= link_to "Return to companies listing", companies_path %>
    </p>
        

</div>