config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root 'pages#home'
  get 'about', to: 'pages#about'
  get 'companies/:id/company_taxpayers', to: 'companies#company_taxpayers', as: :company_taxpayers
  get 'year_index', to: 'taxpayers#year_index'
  get 'inactive_taxpayers', to: 'taxpayers#inactive'
  get 'active_taxpayers', to: 'taxpayers#active'
  get 'login', to: 'sessions#new'
  post 'login', to: 'sessions#create'
  delete 'logout', to: 'sessions#destroy'
  resources :taxpayers
  resources :users
  resources :companies
  resources :years
end

app/views/layouts/_footer.html.erb
<div class="mt-4">
    <footer id="sticky-footer" class="py-4 bg-dark text-white mt-4">
        <div class="container text-center">
            <small> Taxpayer Register | </small>
            <small> Montserrat Customs & Revenue Service | Inland Revenue Department</small>
        </div>
    </footer>
</div>

app/views/layouts/_messages.html.erb
<div class="container">
    <% flash.each do |name, msg| %>
        <div class="alert alert-success alert-dismissible fade show" role="alert">   
            <%= msg %>
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    <% end %>
</div>

app/views/layouts/_navigation.html.backup.erb
<div class="border-bottom pb-1">
  <div class="container ">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!--<a class="navbar-brand" id="logo"  href="#">Taxpayer Register</a>-->
        <%= link_to "Taxpayer Register", root_path, class: "navbar-brand", id: "logo" %>
        
        <% if logged_in? %>
          <div class="navbar-nav flex-row order-md-last">
            <li class="nav-item pt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                </svg>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  <%= current_user.first_name %> <%= current_user.last_name %>
                </a>
                <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to 'Profile', user_path(current_user.id), class: "nav-link"%>
                 <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
                </div>
              </li>
          </div>
        <% else %>
          <div class="navbar-nav flex-row order-md-last">
            <li class="nav-item">
                 <%= link_to 'Login', login_path, class: "nav-link"%>
              </li>
          </div>
        <% end %>
        <% if logged_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
          
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Taxpayers
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Taxpayers", taxpayers_path, class: "dropdown-item" %>
                <%= link_to "Active Taxpayers", active_path, class: "dropdown-item" %>
                <%= link_to "Inactive Taxpayers", inactive_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                  <%= link_to "New Taxpayer", new_taxpayer_path, class:"dropdown-item"%>
                <% end %>
              </div>
            </li>
            
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Companies
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Companies", companies_path, class: "dropdown-item" %>
                <%= link_to "Active Taxpayers", active_path, class: "dropdown-item" %>
                <%= link_to "Inactive Taxpayers", inactive_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                  <%= link_to "New Company", new_company_path, class:"dropdown-item"%>
                <% end %>
              </div>
            </li>
            
            
            <% if current_user.access_level == "Admin" %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Users
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Users", users_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" %>
                  <%= link_to "New User", new_user_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        
      </nav>
  </div>
</div>

app/views/layouts/_navigation.html.erb
<div class="border-bottom pb-1">
  <div class="container ">
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <!--<a class="navbar-brand" id="logo"  href="#">Taxpayer Register</a>-->
        <%= link_to "Taxpayer Register", root_path, class: "navbar-brand", id: "logo" %>
        
        <% if logged_in? %>
          <div class="navbar-nav flex-row order-md-last">
            <li class="nav-item pt-1">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-house-door-fill" viewBox="0 0 16 16">
                  <path d="M6.5 14.5v-3.505c0-.245.25-.495.5-.495h2c.25 0 .5.25.5.5v3.5a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5v-7a.5.5 0 0 0-.146-.354L13 5.793V2.5a.5.5 0 0 0-.5-.5h-1a.5.5 0 0 0-.5.5v1.293L8.354 1.146a.5.5 0 0 0-.708 0l-6 6A.5.5 0 0 0 1.5 7.5v7a.5.5 0 0 0 .5.5h4a.5.5 0 0 0 .5-.5z"/>
                </svg>
            </li>
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                  <%= current_user.first_name %> <%= current_user.last_name %>
                </a>
                <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to 'Profile', user_path(current_user.id), class: "nav-link"%>
                 <%= link_to 'Logout', logout_path, class: "nav-link", method: :delete %>
                </div>
              </li>
          </div>
        <% else %>
          <div class="navbar-nav flex-row order-md-last">
            <li class="nav-item">
                 <%= link_to 'Login', login_path, class: "nav-link"%>
              </li>
          </div>
        <% end %>
        <% if logged_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            
          
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Taxpayers
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Taxpayers", taxpayers_path, class: "dropdown-item" %>
                <%= link_to "Tax Year Register", year_index_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                  <%= link_to "New Taxpayer", new_taxpayer_path, class:"dropdown-item"%>
                <% end %>
              </div>
            </li>
            
            
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Companies
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Companies", companies_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" or current_user.access_level =="Registrar" %>
                  <%= link_to "New Company", new_company_path, class:"dropdown-item"%>
                <% end %>
              </div>
            </li>
            
            
            <% if current_user.access_level == "Admin" %>
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle " href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-expanded="false">
                Users
              </a>
              <div class="dropdown-content" aria-labelledby="navbarDropdown">
                <%= link_to "All Users", users_path, class: "dropdown-item" %>
                <% if current_user.access_level == "Admin" %>
                  <%= link_to "New User", new_user_path, class: "dropdown-item" %>
                <% end %>
              </div>
            </li>
            <% end %>
          </ul>
        </div>
        <% end %>
        
      </nav>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>IncomeRegister</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
  <div id="page-content">
  <body class = "d-flex flex-column">
    
    <%= render 'layouts/navigation' %>
    <%= render 'layouts/messages' %>
    <%= yield %>
    </div>
  <%= render 'layouts/footer' %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!doctype html>
<html>
  <head>
    <meta name="viewport">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <!--<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">-->
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <%= wicked_pdf_javascript_include_tag "number_pages" %>
  </head>
  <body>
      <%= yield %>
  </body>
</html>